# This file is machine-generated - editing it directly is not advised

[[AMP]]
deps = ["ASE", "BenchmarkTools", "JuLIP", "LinearAlgebra", "PyCall", "Requires", "Test"]
git-tree-sha1 = "62da3d07bcd8348695bd760d078c77cefb390537"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/AMP.jl.git"
uuid = "8c5b52c7-7933-4e29-b3e0-9d1a7d7165c4"
version = "0.1.0"

[[CHSF]]
deps = ["BenchmarkTools", "JuLIP", "LinearAlgebra"]
git-tree-sha1 = "970731d2b9cba60c706a73bac798bad7fe84de3d"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/CHSF.jl.git"
uuid = "cb5341de-5fb8-11ea-0ad4-91a81b4b8b32"
version = "0.1.2"

[[DScribe]]
deps = ["ASE", "BenchmarkTools", "JuLIP", "LinearAlgebra", "PyCall", "Test"]
git-tree-sha1 = "c163237859e4e77a058d20d4fd37a46614d422da"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/Dscribe.jl.git"
uuid = "fc698248-5163-421b-9ee2-8b62db393dc1"
version = "0.1.0"

[[MBTR]]
deps = ["ASE", "BenchmarkTools", "JuLIP", "LinearAlgebra", "PyCall", "Requires", "Test"]
git-tree-sha1 = "0ba36130340c97e2957088146f6a64544bc9dbc5"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/MBTR.jl.git"
uuid = "9eff7b03-5cd4-4856-9b32-92c85ebe06b9"
version = "0.1.0"

[[QUIP]]
deps = ["ASE", "BenchmarkTools", "JuLIP", "LinearAlgebra", "PyCall", "Test"]
git-tree-sha1 = "6e30aafca83f3721d37f5993bace738d35dcad32"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/QUIP.jl.git"
uuid = "5b5851ca-98f8-4ad3-91b3-e58310a75415"
version = "0.1.0"

[[SOAPlite]]
deps = ["ASE", "BenchmarkTools", "JuLIP", "LinearAlgebra", "PyCall", "Test"]
git-tree-sha1 = "cf3058e731e371027869657f335979e45469cd80"
repo-rev = "master"
repo-url = "https://github.com/DescriptorZoo/SOAPlite.jl.git"
uuid = "fad40735-9ed7-43f8-a6f6-f9b1a0963de7"
version = "0.1.0"
